# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import enum
from typing import Optional


class BookStatus(enum.StrEnum):
    AVAILABLE = "available"
    CHECKED_OUT = "checked_out"
    OVERDUE = "overdue"


@dataclasses.dataclass()
class Book:
    id: int
    title: str
    status: Optional[BookStatus]
