# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import enum
import pydantic
from typing import Optional


class Operator(str, enum.Enum):
    EQ = "="
    GT = ">"
    LT = "<"
    GTEQ = ">="
    LTEQ = "<="


class Operation(pydantic.BaseModel):
    a: Optional[int]
    b: Optional[int]
    operation: Optional[Operator]
